import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/styles.module.css";
import { Heading, Route } from "../components/heading";
import Link from "next/link";

export default function About() {
    return (
        <>
            <Head>
                <title>About | Eventster</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <Heading />
                <h1 className='text-6xl'>About Us</h1>
                <div className={styles.center}>
                    <p className={"w-6/12 mt-16"}>
                        Welcome to our website! We are so glad you are here.
                        <br />
                        <br />
                        We are a team of passionate professionals dedicated to
                        providing the best possible service to our customers.
                        Our mission is to provide our customers with the highest
                        quality products and services, while also providing them
                        with the best customer service experience possible. We
                        strive to make sure that our customers are always
                        satisfied with their purchases and that they have a
                        positive experience with us. We offer AI-powered event
                        planning.
                        <br />
                        <br />
                        We are committed to providing our customers with the
                        best possible experience and strive to make sure that
                        they are always happy with their purchases. We are
                        constantly looking for ways to improve our services and
                        products to ensure our customers are always satisfied.
                        <br />
                        <br />
                        If you have any questions or comments, please feel free
                        to contact us. We look forward to hearing from you and
                        helping you with your online needs. Thank you for
                        visiting our website!
                    </p>
                </div>
            </main>
        </>
    );
}
