import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/styles.module.css";
import { Heading, Route } from "../components/heading";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Eventster</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <Heading />
                <h1 className='text-8xl'>This is Eventster.</h1>
                <div className={styles.center}>
                    <h1 className='text-4xl'>
                        AI-powered event planning consultation services{" "}
                    </h1>
                    <div className={styles.thirteen}>
                        <h1 className={"font-semibold text-4xl"}>
                            <Link href='/chat'>
                                <Image
                                    src='/chevron-right.svg'
                                    alt='chevron-right'
                                    width={40}
                                    height={40}
                                />
                            </Link>
                        </h1>
                    </div>
                </div>
                <div className={styles.grid}>
                    <div className={styles.card}>&nbsp;</div>
                </div>
            </main>
        </>
    );
}
